version: '3'
services:
  dev_paperboy_mysql:
    image: mysql:5.7
    container_name: dev_paperboy_mysql
    env_file: .env.dev
    environment:
      MYSQL_ROOT_PASSWORD: paperboy
    ports:
      - 127.0.0.1:$DEV_PAPERBOY_MYSQL_PORT:3306

  paperboy_mysql:
    image: mysql:5.7
    container_name: paperboy_mysql
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: paperboy
    ports:
      - 127.0.0.1:$LOCAL_PAPERBOY_MYSQL_PORT:3306
    volumes:
      - paperboy_mysql:/var/lib/mysql


  #################### Base  ####################

  base: &base
    image: darthjee/dev_paperboy
    volumes:
      - ./source:/home/app/app
    links:
      - dev_paperboy_mysql:mysql
    env_file: .env.dev


  base_build:
    <<: *base
    build:
      context: .
      dockerfile: Dockerfile.dev_paperboy
    command: echo done

  production_base_build:
    image: darthjee/production_paperboy
    env_file: .env.dev
    environment:
      RAILS_ENV: production
    build:
      context: .
      dockerfile: Dockerfile.production_paperboy
    command: echo done
  #################### CONTAINERS ####################

  paperboy_app:
    <<: *base
    container_name: paperboy_app
    command: /bin/bash bin/server.sh
    depends_on: [base_build]
    ports:
      - 127.0.0.1:3000:3000
    environment:
      - RAILS_ENV=development
      - PAPERBOY_MYSQL_PORT=3306

  paperboy_tests:
    <<: *base
    container_name: paperboy_tests
    command: /bin/bash bin/tests.sh
    depends_on: [base_build]
    environment:
      - RAILS_ENV=test

  paperboy_root:
    <<: *base
    user: root
    container_name: paperboy_root
    command: /bin/bash
    depends_on: [base_build]

  paperboy_production:
    env_file: .env.production
    container_name: paperboy_production
    image: $PRODUCTION_IMAGE

  volumes:
    paperboy_mysql
