FROM darthjee/paperboy-base:0.0.5

WORKDIR /home/app/app
COPY --chown=app:app source/Gemfile* /home/app/app/
COPY --chown=app:app source/bower.json /home/app/app/

RUN bundle install

USER root
RUN npm install -g yarn

USER app
RUN bower install
