version: '3'
services:
  paperboy_mysql:
    image: mysql:5.7
    container_name: paperboy_mysql
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: paperboy
    ports:
      - 127.0.0.1:$PAPERBOY_MYSQL_PORT:3306
  #################### Base  ####################

  base: &base
    image: darthjee/paperboy
    volumes:
      - ./source:/home/app/app
    links:
      - paperboy_mysql:mysql
    env_file: .env


  base_build:
    <<: *base
    build:
      context: .
      dockerfile: Dockerfile.paperboy
    command: echo done

  #################### CONTAINERS ####################

  paperboy_app:
    <<: *base
    container_name: paperboy_app
    command: /bin/bash bin/server.sh
    depends_on: [base_build]
    ports:
      - 127.0.0.1:3000:3000
    environment:
      - RAILS_ENV=development
      - PAPERBOY_MYSQL_PORT=3306

  paperboy_tests:
    <<: *base
    container_name: paperboy_tests
    command: /bin/bash bin/tests.sh
    depends_on: [base_build]
    environment:
      - RAILS_ENV=test

  paperboy_root:
    <<: *base
    user: root
    container_name: paperboy_root
    command: /bin/bash
    depends_on: [base_build]

  paperboy_production:
    env_file: .env.production
    container_name: paperboy_production
    image: darthjee/production_paperboy
    build:
      context: .
      dockerfile: Dockerfile.production_paperboy

  paperboy_circleci:
    image: darthjee/circleci_paperboy-base
    build:
      context: .
      dockerfile: Dockerfile.circleci_paperboy-base
    container_name: paperboy_circleci
    command: /bin/bash
    environment:
      - RAILS_ENV=test
