FROM darthjee/paperboy-base:0.0.4

WORKDIR /home/app/app
COPY --chown=app:app source/Gemfile* /home/app/app/
COPY --chown=app:app source/bower.json /home/app/app/

RUN bundle install

USER app
RUN bower install
